### ISSUE TITLE
error occurred when trying to render frame 1

### ISSUE THREAD

**Issue by uditkumar01** [marcusstenbeck/remotion-template-audiogram#1] opened 2022-03-24 16:29 UTC
![Screenshot from 2022-03-24 21-46-29](https://user-images.githubusercontent.com/55291327/159962127-143264ff-33c9-4cef-b67a-dcc830992fd3.png)

I have installed all the packages as mentioned in the docs.
I am using `Ubuntu 20.04.4 LTS (64 bit)` & `ffmpeg 4.2.4-1ubuntu0.1`
Have installed additional packages for Chrome/Puppeteer as mention [here](https://www.remotion.dev/docs/)
Here is the [repo link](https://github.com/uditkumar01/podcast-remotion)
Even `remotion-template-audiogram` is not working for me

**Comment by JonnyBurger** [comment] 2022-03-24 19:10
Hi @uditkumar01!
Sorry for the problem and thanks for supplying a reproduction. I cloned it and was able to build, so I suppose it has something to do with the browser or the environment.

Could you add the `--log=verbose` flag to the render command to possibly surface some more information?

**Comment by uditkumar01** [comment] 2022-03-24 21:40
> Hi @uditkumar01! Sorry for the problem and thanks for supplying a reproduction. I cloned it and was able to build, so I suppose it has something to do with the browser or the environment.
> 
> Could you add the `--log=verbose` flag to the render command to possibly surface some more information?

Thank you for your quick response. 
![Screenshot (5)](https://user-images.githubusercontent.com/55291327/160014728-a7a7cd70-dc4e-457c-a9bf-219a25dab635.png)

**Comment by JonnyBurger** [comment] 2022-03-25 09:41
Hi @uditkumar01!

The problem seems to be that you Chromium instance does not seem to support the MP3 codec as it is proprietary and not always included on Linux. You could verify this by dropping the MP3 into the browser that is used for rendering and checking  whether it loads or not.

Apologies that the error message is really unclear.
I've made a new issue in the main Remotion repository to file it: https://github.com/remotion-dev/remotion/issues/897

**Comment by uditkumar01** [comment] 2022-03-25 13:28
> 

Thanks a lot @JonnyBurger , u r correct its related to Chromium, re-installation worked for me. 🔥

**Comment by JonnyBurger** [comment] 2022-03-25 13:36
@uditkumar01 Nice, glad your problem got resolved! I'll close this, but leave the other issue open on the Remotion repository.

**Closed by JonnyBurger** 2022-03-25 13:36 UTC
